apiVersion: apps/v1
kind: Deployment
metadata:
  name: toys-deployment
  labels:
    app: toys
spec:
  replicas: 2
  selector:
    matchLabels:
      app: toys
  template:
    metadata:
      labels:
        app: toys
    spec:
      containers:
      - name: toys
        image: 413117505476.dkr.ecr.us-east-1.amazonaws.com/shopping-site-toys:daf50583894e25e8de24a525db469a065e714219
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: toys-service
  labels:
    app: toys
spec:
  type: ClusterIP
  selector:
    app: toys
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
